name: Commerce Product taxonomy filter
type: module
description: 'Provides taxonomy filter with depth for Drupal Commerce product entity.'
package: Commerce
# core: 8.x

dependencies:
  - commerce:commerce
  - drupal:system (>= 8.6)

# Information added by Drupal.org packaging script on 2018-11-02
version: '8.x-2.x-dev'
core: '8.x'
project: 'product_taxonomy_filter'
datestamp: 1541166784
